<?php
/*
 * @provenance M1 (written wrapper, promoted via gate F 2026-08-03; the
 *   whole page is the era-final capture verbatim in one @O fence -- all
 *   five dynamic regions are template-edit:20170124 deploy-time constants,
 *   incl. the page's own constant initCode, so gate F gates every line)
 * @written 2026-08-03 (generated by tools/derender.py)
 * @evidence 9 era captures byte-stable since 20170124 (offline gate,
 *   tests/test_masks.py); render diffed against the era-final reference
 *   (tests/test_render_diff.py)
 * @contains
 *   archive/commoncrawl/warc-bodies/20181020_tanktrouble.com_embed.php.txt lines=1-119
 */
/* @O-begin source=archive/commoncrawl/warc-bodies/20181020_tanktrouble.com_embed.php.txt lines=1-119 */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
		<meta name="keywords" content="2 player, game, 3 player, multiplayer, tank, trouble, mads purup, brian christensen" />
		<meta name="description" content="Most explosive 2 player tank game online! Great for savage coffee breaks at the office." />
		<meta name="author" content="www.purup.com" />
		<meta name="robots" content="all" />
		<title>TANK TROUBLE</title>
		<link href="includes/styles.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="includes/swfobject.js"></script>

	    <script type="text/javascript">
		    function removeAdSwf() {
		        document.getElementById("preloader").style.visibility = "hidden";
		        document.getElementById("TankTrouble").style.visibility = "visible";
    			setTimeout("window.document.TankTroubleGame.focus();", 1);
                showLink();
		    }
		    function noAdsReturned() {
		        document.getElementById("preloader").style.visibility = "hidden";
		        document.getElementById("TankTrouble").style.visibility = "visible";
    			setTimeout("window.document.TankTroubleGame.focus();", 1);
                showLink();
		    }
            
            function showLink() {
                // Insert link
                var linkDiv = document.createElement('div');
                document.getElementById('centerColumn').appendChild(linkDiv);
                var link = document.createElement('a');
                var linkImg = document.createElement('img');
                link.appendChild(linkImg);
                linkDiv.appendChild(link);
				linkImg.style.display='block';
				linkImg.alt='Go to TankTrouble.com';
                linkImg.title='Go to TankTrouble.com';
                linkImg.src='images/TankTroubleBanner636x75.png';
                link.onclick=function() {
                    window.open('http://www.tanktrouble.com/?r=Link%20embed', '_blank');
                };
                link.style.cursor='pointer';
				linkDiv.style.position='absolute';
                linkDiv.style.top='7px';
                linkDiv.style.left='38px';

				
				var	showCallToAction = function() {
					var callToAction = document.createElement('img');
					callToAction.style.display='block';
					callToAction.id='callToAction';
					callToAction.alt='Go to TankTrouble.com';
					callToAction.title='Go to TankTrouble.com';
					callToAction.src='images/callToAction0' + Math.floor(Math.random() * 5) + '.png';
	            	link.appendChild(callToAction);
					setTimeout(hideCallToAction, 15000);	
				}
				
				var	hideCallToAction = function() {
					var callToAction = document.getElementById('callToAction');
	            	link.removeChild(callToAction);
					setTimeout(showCallToAction, 5000);
				}
				
				setTimeout(showCallToAction, 60000);
				
				/*
				// Make logo smaller and move game up when game starts.
				// Javascript calls through getURL no longer allowed cross domain.
				var pollIfStarted = setInterval(function() {
					if(document.getElementById('TankTrouble').style.top === '-10px') {
                        linkImg.style.width = '318px';
                        linkDiv.style.left = '197px';
                        linkDiv.style.top = '-8px';
                        clearInterval(pollIfStarted);
                    }
                }, 100);
                */
            }
	    </script>
	</head>
	<body>
		<!-- Google tracking code -->
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-3233847-1', 'auto');
			ga('require', 'displayfeatures');
            ga('send', 'pageview', {'dimension1': 'no'});
		</script>

		<!-- Game container -->
		<div id="centerColumn" style="margin: auto; width: 712px; position: absolute; top: 10px;">
		
			<div id="TankTrouble" style="position: absolute; top: 70px;">
			</div>
		</div>
		<!-- Embed game -->
		<script type="text/javascript">
			<!--
			//REMEMBER TO CHANGE THE VERSION IN logIn.php AND game.php AS WELL!!!
			var tt = new SWFObject("includes/TankTrouble_v4.0.swf", "TankTroubleGame", "712", "490", "8", "#ffffff");
			tt.addParam("allowScriptAccess", "sameDomain");
			tt.addParam("menu", "false");
			tt.addParam("quality", "high");
			tt.addParam("bgcolor", "#ffffff");

tt.addParam('FlashVars','initCode=bnVtVXNlcnM9MA==');		
		    tt.write("TankTrouble");
	        setTimeout("window.document.TankTroubleGame.focus();", 1);
            showLink();
			// -->
		</script>
		
	</body>
</html>

<?php /* @O-end */
